name: publish
on:
  push:
    branches: ["master"]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/hlegendre/gmvault-docker-healthchecksio:latest
          docker run ghcr.io/hlegendre/gmvault-docker-healthchecksio:latest
          docker push ghcr.io/hlegendre/gmvault-docker-healthchecksio:latest
